# Site settings
author: Robert Salaiz
title: The first step to something better
header-img: img/home-bg.png
email: work.salaizrm@gmail.com
copyright_name: Robert Salaiz
description: > # this means to ignore newlines until "baseurl:"
  Why I want to learn coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Salaizrm

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
